FROM almalinux:9 
LABEL project="expense" \
      component="frontend" \
      environment="dev" \
      trainer="siva"

# LABEL is used for just informational purpose, with this we will not get any functionality changes and these are used for filterization puprpose.
# LABEL is the key value pair 
# If we are having 1000 images if we want to filetr any perticular image LABEL is usefull for filterization purpose.