FROM almalinux:9 
LABEL project="expense" \
      component="frontend" \
      environment="dev" \
      trainer="siva"

# LABEL is used for just informational purpose, with this we will not get any functionality changes and these are used for filterization puprpose.
# LABEL is the key value pair 