ARG vesrion
FROM almalinux:${vesrion:-9}
ENV course="devops with AWS" \
    trainer="ramu gorla" \
    duration="120HRS"
ARG USERNAME=RAMUGORLA
ENV USERNAME=$USERNAME
# 16th line is to make the ARG variables accessible inside the container
RUN echo "Hello ${USERNAME}, Base OS vesrion is : $version" > /tmp/devops.txt
CMD ["sleep", "100"]

# ARG instruction can be the 1st instruction when we want to pass or supply the version to the base OS after FROM instruction ARG instrucion will not work.

