FROM almalinux:9 
RUN dnf install nginx -y 
# Run instruction is used to install packages and do the configuration on top of base os which has been represents by FROM instruction 
# RUN instruction will execute at the time of image building.